"""Add order_blank_item model

Revision ID: 49de5e2f8612
Revises: 0006_plid
Create Date: 2026-07-01 00:47:16.304010

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '49de5e2f8612'
down_revision: str | Sequence[str] | None = '0006_plid'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_blank_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.BigInteger(), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('is_new', sa.Integer(), nullable=False),
    sa.Column('focus', sa.String(length=64), nullable=False),
    sa.Column('abc_group', sa.String(length=64), nullable=False),
    sa.Column('item_type', sa.String(length=128), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=False),
    sa.Column('weight_gr', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['order_blank_upload.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_blank_item_sku'), 'order_blank_item', ['sku'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_blank_item_sku'), table_name='order_blank_item')
    op.drop_table('order_blank_item')
    # ### end Alembic commands ###
