"""add_forecast_model

Revision ID: 400630c9cde5
Revises: 49de5e2f8612
Create Date: 2026-07-01 00:43:58.961400

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '400630c9cde5'
down_revision: str | Sequence[str] | None = '49de5e2f8612'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('predicted_qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_month'), 'forecast', ['month'], unique=False)
    op.create_index(op.f('ix_forecast_sku'), 'forecast', ['sku'], unique=False)
    op.create_index(op.f('ix_forecast_store_id'), 'forecast', ['store_id'], unique=False)
    op.drop_index(op.f('ix_order_blank_upload_applied_at'), table_name='order_blank_upload')
    op.drop_index(op.f('ix_order_blank_upload_status_applied'), table_name='order_blank_upload')
    op.drop_index(op.f('ix_product_nom_number'), table_name='product')
    op.drop_column('sales_monthly', 'orders_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_monthly', sa.Column('orders_count', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_product_nom_number'), 'product', ['nom_number'], unique=False)
    op.create_index(op.f('ix_order_blank_upload_status_applied'), 'order_blank_upload', ['status', 'applied_at'], unique=False)
    op.create_index(op.f('ix_order_blank_upload_applied_at'), 'order_blank_upload', ['applied_at'], unique=False)
    op.drop_index(op.f('ix_forecast_store_id'), table_name='forecast')
    op.drop_index(op.f('ix_forecast_sku'), table_name='forecast')
    op.drop_index(op.f('ix_forecast_month'), table_name='forecast')
    op.drop_table('forecast')
    # ### end Alembic commands ###
