"""add recommended_qty to forecast

Revision ID: 8e129cde1a38
Revises: 400630c9cde5
Create Date: 2026-07-14 15:18:24.742466

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8e129cde1a38'
down_revision: str | Sequence[str] | None = '400630c9cde5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast', sa.Column('recommended_qty', sa.Numeric(precision=10, scale=2), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast', 'recommended_qty')
    # ### end Alembic commands ###
